C     -*- fortran -*-
C     This file is autogenerated with f2py (version:2)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pywrapFirstHorzTideStrain3 (FirstHorzTideStrain
     &3f2pywrap, ETime, Slat, Slong, Salt, Azim)
      external FirstHorzTideStrain3
      real ETime
      real Slat
      real Slong
      real Salt
      real Azim
      double precision FirstHorzTideStrain3f2pywrap, FirstHorzTide
     &Strain3
      FirstHorzTideStrain3f2pywrap = FirstHorzTideStrain3(ETime, S
     &lat, Slong, Salt, Azim)
      end


      subroutine f2pywrapSecondHorzTideStrain4 (SecondHorzTideStra
     &in4f2pywrap, ETime, Slat, Slong, Salt)
      external SecondHorzTideStrain4
      real ETime
      real Slat
      real Slong
      real Salt
      double precision SecondHorzTideStrain4f2pywrap, SecondHorzTi
     &deStrain4
      SecondHorzTideStrain4f2pywrap = SecondHorzTideStrain4(ETime,
     & Slat, Slong, Salt)
      end


      subroutine f2pywrapGravityTide6 (GravityTide6f2pywrap, ETime
     &, Slat, Slong, Salt)
      external GravityTide6
      real ETime
      real Slat
      real Slong
      real Salt
      double precision GravityTide6f2pywrap, GravityTide6
      GravityTide6f2pywrap = GravityTide6(ETime, Slat, Slong, Salt
     &)
      end


      subroutine f2pywrapTiltTide7 (TiltTide7f2pywrap, ETime, Slat
     &, Slong, Salt)
      external TiltTide7
      real ETime
      real Slat
      real Slong
      real Salt
      double precision TiltTide7f2pywrap, TiltTide7
      TiltTide7f2pywrap = TiltTide7(ETime, Slat, Slong, Salt)
      end


      subroutine f2pywrapDryTide8 (DryTide8f2pywrap, ETime, Slat, 
     &Slong, Salt)
      external DryTide8
      real ETime
      real Slat
      real Slong
      real Salt
      double precision DryTide8f2pywrap, DryTide8
      DryTide8f2pywrap = DryTide8(ETime, Slat, Slong, Salt)
      end


      subroutine f2pywrapShearTide9 (ShearTide9f2pywrap, ETime, Sl
     &at, Slong, Salt)
      external ShearTide9
      real ETime
      real Slat
      real Slong
      real Salt
      double precision ShearTide9f2pywrap, ShearTide9
      ShearTide9f2pywrap = ShearTide9(ETime, Slat, Slong, Salt)
      end


      subroutine f2pywrapTid2 (Tid2f2pywrap, SLAT, SLONG, SH, KIND
     &, ALPHA, astron)
      external Tid2
      real SLAT
      real SLONG
      real SH
      integer KIND
      real ALPHA
      real astron
      real Tid2f2pywrap, Tid2
      Tid2f2pywrap = Tid2(SLAT, SLONG, SH, KIND, ALPHA, astron)
      end

