/* File: EtideAsFuncmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * See http://cens.ioc.ee/projects/f2py2e/
 * Generation date: Thu Aug 08 15:12:47 2013
 * $Revision:$
 * $Date:$
 * Do not edit this file directly unless you know what you are doing!!!
 */
#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include "fortranobject.h"
/*need_includes0*/

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *EtideAsFunc_error;
static PyObject *EtideAsFunc_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) _F2PYWRAP##F
#else
#define F_WRAPPEDFUNC(f,F) _f2pywrap##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) _F2PYWRAP##F##_
#else
#define F_WRAPPEDFUNC(f,F) _f2pywrap##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) F2PYWRAP##F
#else
#define F_WRAPPEDFUNC(f,F) f2pywrap##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_WRAPPEDFUNC(f,F) F2PYWRAP##F##_
#else
#define F_WRAPPEDFUNC(f,F) f2pywrap##f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_WRAPPEDFUNC_US(f,F) F_WRAPPEDFUNC(f##_,F##_)
#else
#define F_WRAPPEDFUNC_US(f,F) F_WRAPPEDFUNC(f,F)
#endif

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyFloat_Check(obj)) {
#ifdef __sgi
    *v = PyFloat_AsDouble(obj);
#else
    *v = PyFloat_AS_DOUBLE(obj);
#endif
    return 1;
  }
  tmp = PyNumber_Float(obj);
  if (tmp) {
#ifdef __sgi
    *v = PyFloat_AsDouble(tmp);
#else
    *v = PyFloat_AS_DOUBLE(tmp);
#endif
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = EtideAsFunc_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int float_from_pyobj(float* v,PyObject *obj,const char *errmess) {
  double d=0.0;
  if (double_from_pyobj(&d,obj,errmess)) {
    *v = (float)d;
    return 1;
  }
  return 0;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyInt_Check(obj)) {
    *v = (int)PyInt_AS_LONG(obj);
    return 1;
  }
  tmp = PyNumber_Int(obj);
  if (tmp) {
    *v = PyInt_AS_LONG(tmp);
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = EtideAsFunc_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_WRAPPEDFUNC(firsthorztidestrain3,FIRSTHORZTIDESTRAIN3)(double*,float*,float*,float*,float*,float*);
extern void F_WRAPPEDFUNC(secondhorztidestrain4,SECONDHORZTIDESTRAIN4)(double*,float*,float*,float*,float*);
extern void F_WRAPPEDFUNC(gravitytide6,GRAVITYTIDE6)(double*,float*,float*,float*,float*);
extern void F_WRAPPEDFUNC(tilttide7,TILTTIDE7)(double*,float*,float*,float*,float*);
extern void F_WRAPPEDFUNC(drytide8,DRYTIDE8)(double*,float*,float*,float*,float*);
extern void F_WRAPPEDFUNC(sheartide9,SHEARTIDE9)(double*,float*,float*,float*,float*);
extern void F_FUNC(Ntide1,NTIDE1)(float*,float*);
extern void F_WRAPPEDFUNC(tid2,TID2)(float*,float*,float*,float*,int*,float*,float*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/**************************** FirstHorzTideStrain3 ****************************/
static char doc_f2py_rout_EtideAsFunc_FirstHorzTideStrain3[] = "\
Function signature:\n\
  FirstHorzTideStrain3 = FirstHorzTideStrain3(ETime,Slat,Slong,Salt,Azim)\n\
Required arguments:\n"
"  ETime : input float\n"
"  Slat : input float\n"
"  Slong : input float\n"
"  Salt : input float\n"
"  Azim : input float\n"
"Return objects:\n"
"  FirstHorzTideStrain3 : float";
/* extern void F_WRAPPEDFUNC(firsthorztidestrain3,FIRSTHORZTIDESTRAIN3)(double*,float*,float*,float*,float*,float*); */
static PyObject *f2py_rout_EtideAsFunc_FirstHorzTideStrain3(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,float*,float*,float*,float*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double FirstHorzTideStrain3 = 0;
  float ETime = 0;
  PyObject *ETime_capi = Py_None;
  float Slat = 0;
  PyObject *Slat_capi = Py_None;
  float Slong = 0;
  PyObject *Slong_capi = Py_None;
  float Salt = 0;
  PyObject *Salt_capi = Py_None;
  float Azim = 0;
  PyObject *Azim_capi = Py_None;
  static char *capi_kwlist[] = {"ETime","Slat","Slong","Salt","Azim",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOO:EtideAsFunc.FirstHorzTideStrain3",\
    capi_kwlist,&ETime_capi,&Slat_capi,&Slong_capi,&Salt_capi,&Azim_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable FirstHorzTideStrain3 */
  /* Processing variable Slong */
    f2py_success = float_from_pyobj(&Slong,Slong_capi,"EtideAsFunc.FirstHorzTideStrain3() 3rd argument (Slong) can't be converted to float");
  if (f2py_success) {
  /* Processing variable Slat */
    f2py_success = float_from_pyobj(&Slat,Slat_capi,"EtideAsFunc.FirstHorzTideStrain3() 2nd argument (Slat) can't be converted to float");
  if (f2py_success) {
  /* Processing variable Azim */
    f2py_success = float_from_pyobj(&Azim,Azim_capi,"EtideAsFunc.FirstHorzTideStrain3() 5th argument (Azim) can't be converted to float");
  if (f2py_success) {
  /* Processing variable Salt */
    f2py_success = float_from_pyobj(&Salt,Salt_capi,"EtideAsFunc.FirstHorzTideStrain3() 4th argument (Salt) can't be converted to float");
  if (f2py_success) {
  /* Processing variable ETime */
    f2py_success = float_from_pyobj(&ETime,ETime_capi,"EtideAsFunc.FirstHorzTideStrain3() 1st argument (ETime) can't be converted to float");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(&FirstHorzTideStrain3,&ETime,&Slat,&Slong,&Salt,&Azim);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("d",FirstHorzTideStrain3);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of ETime*/
  /* End of cleaning variable ETime */
  } /*if (f2py_success) of Salt*/
  /* End of cleaning variable Salt */
  } /*if (f2py_success) of Azim*/
  /* End of cleaning variable Azim */
  } /*if (f2py_success) of Slat*/
  /* End of cleaning variable Slat */
  } /*if (f2py_success) of Slong*/
  /* End of cleaning variable Slong */
  /* End of cleaning variable FirstHorzTideStrain3 */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/************************ end of FirstHorzTideStrain3 ************************/

/*************************** SecondHorzTideStrain4 ***************************/
static char doc_f2py_rout_EtideAsFunc_SecondHorzTideStrain4[] = "\
Function signature:\n\
  SecondHorzTideStrain4 = SecondHorzTideStrain4(ETime,Slat,Slong,Salt)\n\
Required arguments:\n"
"  ETime : input float\n"
"  Slat : input float\n"
"  Slong : input float\n"
"  Salt : input float\n"
"Return objects:\n"
"  SecondHorzTideStrain4 : float";
/* extern void F_WRAPPEDFUNC(secondhorztidestrain4,SECONDHORZTIDESTRAIN4)(double*,float*,float*,float*,float*); */
static PyObject *f2py_rout_EtideAsFunc_SecondHorzTideStrain4(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,float*,float*,float*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double SecondHorzTideStrain4 = 0;
  float ETime = 0;
  PyObject *ETime_capi = Py_None;
  float Slat = 0;
  PyObject *Slat_capi = Py_None;
  float Slong = 0;
  PyObject *Slong_capi = Py_None;
  float Salt = 0;
  PyObject *Salt_capi = Py_None;
  static char *capi_kwlist[] = {"ETime","Slat","Slong","Salt",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO:EtideAsFunc.SecondHorzTideStrain4",\
    capi_kwlist,&ETime_capi,&Slat_capi,&Slong_capi,&Salt_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable SecondHorzTideStrain4 */
  /* Processing variable Slong */
    f2py_success = float_from_pyobj(&Slong,Slong_capi,"EtideAsFunc.SecondHorzTideStrain4() 3rd argument (Slong) can't be converted to float");
  if (f2py_success) {
  /* Processing variable Slat */
    f2py_success = float_from_pyobj(&Slat,Slat_capi,"EtideAsFunc.SecondHorzTideStrain4() 2nd argument (Slat) can't be converted to float");
  if (f2py_success) {
  /* Processing variable Salt */
    f2py_success = float_from_pyobj(&Salt,Salt_capi,"EtideAsFunc.SecondHorzTideStrain4() 4th argument (Salt) can't be converted to float");
  if (f2py_success) {
  /* Processing variable ETime */
    f2py_success = float_from_pyobj(&ETime,ETime_capi,"EtideAsFunc.SecondHorzTideStrain4() 1st argument (ETime) can't be converted to float");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(&SecondHorzTideStrain4,&ETime,&Slat,&Slong,&Salt);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("d",SecondHorzTideStrain4);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of ETime*/
  /* End of cleaning variable ETime */
  } /*if (f2py_success) of Salt*/
  /* End of cleaning variable Salt */
  } /*if (f2py_success) of Slat*/
  /* End of cleaning variable Slat */
  } /*if (f2py_success) of Slong*/
  /* End of cleaning variable Slong */
  /* End of cleaning variable SecondHorzTideStrain4 */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/************************ end of SecondHorzTideStrain4 ************************/

/******************************** GravityTide6 ********************************/
static char doc_f2py_rout_EtideAsFunc_GravityTide6[] = "\
Function signature:\n\
  GravityTide6 = GravityTide6(ETime,Slat,Slong,Salt)\n\
Required arguments:\n"
"  ETime : input float\n"
"  Slat : input float\n"
"  Slong : input float\n"
"  Salt : input float\n"
"Return objects:\n"
"  GravityTide6 : float";
/* extern void F_WRAPPEDFUNC(gravitytide6,GRAVITYTIDE6)(double*,float*,float*,float*,float*); */
static PyObject *f2py_rout_EtideAsFunc_GravityTide6(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,float*,float*,float*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double GravityTide6 = 0;
  float ETime = 0;
  PyObject *ETime_capi = Py_None;
  float Slat = 0;
  PyObject *Slat_capi = Py_None;
  float Slong = 0;
  PyObject *Slong_capi = Py_None;
  float Salt = 0;
  PyObject *Salt_capi = Py_None;
  static char *capi_kwlist[] = {"ETime","Slat","Slong","Salt",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO:EtideAsFunc.GravityTide6",\
    capi_kwlist,&ETime_capi,&Slat_capi,&Slong_capi,&Salt_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable Slong */
    f2py_success = float_from_pyobj(&Slong,Slong_capi,"EtideAsFunc.GravityTide6() 3rd argument (Slong) can't be converted to float");
  if (f2py_success) {
  /* Processing variable GravityTide6 */
  /* Processing variable Slat */
    f2py_success = float_from_pyobj(&Slat,Slat_capi,"EtideAsFunc.GravityTide6() 2nd argument (Slat) can't be converted to float");
  if (f2py_success) {
  /* Processing variable Salt */
    f2py_success = float_from_pyobj(&Salt,Salt_capi,"EtideAsFunc.GravityTide6() 4th argument (Salt) can't be converted to float");
  if (f2py_success) {
  /* Processing variable ETime */
    f2py_success = float_from_pyobj(&ETime,ETime_capi,"EtideAsFunc.GravityTide6() 1st argument (ETime) can't be converted to float");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(&GravityTide6,&ETime,&Slat,&Slong,&Salt);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("d",GravityTide6);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of ETime*/
  /* End of cleaning variable ETime */
  } /*if (f2py_success) of Salt*/
  /* End of cleaning variable Salt */
  } /*if (f2py_success) of Slat*/
  /* End of cleaning variable Slat */
  /* End of cleaning variable GravityTide6 */
  } /*if (f2py_success) of Slong*/
  /* End of cleaning variable Slong */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/**************************** end of GravityTide6 ****************************/

/********************************* TiltTide7 *********************************/
static char doc_f2py_rout_EtideAsFunc_TiltTide7[] = "\
Function signature:\n\
  TiltTide7 = TiltTide7(ETime,Slat,Slong,Salt)\n\
Required arguments:\n"
"  ETime : input float\n"
"  Slat : input float\n"
"  Slong : input float\n"
"  Salt : input float\n"
"Return objects:\n"
"  TiltTide7 : float";
/* extern void F_WRAPPEDFUNC(tilttide7,TILTTIDE7)(double*,float*,float*,float*,float*); */
static PyObject *f2py_rout_EtideAsFunc_TiltTide7(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,float*,float*,float*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double TiltTide7 = 0;
  float ETime = 0;
  PyObject *ETime_capi = Py_None;
  float Slat = 0;
  PyObject *Slat_capi = Py_None;
  float Slong = 0;
  PyObject *Slong_capi = Py_None;
  float Salt = 0;
  PyObject *Salt_capi = Py_None;
  static char *capi_kwlist[] = {"ETime","Slat","Slong","Salt",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO:EtideAsFunc.TiltTide7",\
    capi_kwlist,&ETime_capi,&Slat_capi,&Slong_capi,&Salt_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable TiltTide7 */
  /* Processing variable Slong */
    f2py_success = float_from_pyobj(&Slong,Slong_capi,"EtideAsFunc.TiltTide7() 3rd argument (Slong) can't be converted to float");
  if (f2py_success) {
  /* Processing variable Slat */
    f2py_success = float_from_pyobj(&Slat,Slat_capi,"EtideAsFunc.TiltTide7() 2nd argument (Slat) can't be converted to float");
  if (f2py_success) {
  /* Processing variable Salt */
    f2py_success = float_from_pyobj(&Salt,Salt_capi,"EtideAsFunc.TiltTide7() 4th argument (Salt) can't be converted to float");
  if (f2py_success) {
  /* Processing variable ETime */
    f2py_success = float_from_pyobj(&ETime,ETime_capi,"EtideAsFunc.TiltTide7() 1st argument (ETime) can't be converted to float");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(&TiltTide7,&ETime,&Slat,&Slong,&Salt);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("d",TiltTide7);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of ETime*/
  /* End of cleaning variable ETime */
  } /*if (f2py_success) of Salt*/
  /* End of cleaning variable Salt */
  } /*if (f2py_success) of Slat*/
  /* End of cleaning variable Slat */
  } /*if (f2py_success) of Slong*/
  /* End of cleaning variable Slong */
  /* End of cleaning variable TiltTide7 */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of TiltTide7 ******************************/

/********************************** DryTide8 **********************************/
static char doc_f2py_rout_EtideAsFunc_DryTide8[] = "\
Function signature:\n\
  DryTide8 = DryTide8(ETime,Slat,Slong,Salt)\n\
Required arguments:\n"
"  ETime : input float\n"
"  Slat : input float\n"
"  Slong : input float\n"
"  Salt : input float\n"
"Return objects:\n"
"  DryTide8 : float";
/* extern void F_WRAPPEDFUNC(drytide8,DRYTIDE8)(double*,float*,float*,float*,float*); */
static PyObject *f2py_rout_EtideAsFunc_DryTide8(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,float*,float*,float*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double DryTide8 = 0;
  float ETime = 0;
  PyObject *ETime_capi = Py_None;
  float Slat = 0;
  PyObject *Slat_capi = Py_None;
  float Slong = 0;
  PyObject *Slong_capi = Py_None;
  float Salt = 0;
  PyObject *Salt_capi = Py_None;
  static char *capi_kwlist[] = {"ETime","Slat","Slong","Salt",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO:EtideAsFunc.DryTide8",\
    capi_kwlist,&ETime_capi,&Slat_capi,&Slong_capi,&Salt_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable Slong */
    f2py_success = float_from_pyobj(&Slong,Slong_capi,"EtideAsFunc.DryTide8() 3rd argument (Slong) can't be converted to float");
  if (f2py_success) {
  /* Processing variable Slat */
    f2py_success = float_from_pyobj(&Slat,Slat_capi,"EtideAsFunc.DryTide8() 2nd argument (Slat) can't be converted to float");
  if (f2py_success) {
  /* Processing variable Salt */
    f2py_success = float_from_pyobj(&Salt,Salt_capi,"EtideAsFunc.DryTide8() 4th argument (Salt) can't be converted to float");
  if (f2py_success) {
  /* Processing variable DryTide8 */
  /* Processing variable ETime */
    f2py_success = float_from_pyobj(&ETime,ETime_capi,"EtideAsFunc.DryTide8() 1st argument (ETime) can't be converted to float");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(&DryTide8,&ETime,&Slat,&Slong,&Salt);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("d",DryTide8);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of ETime*/
  /* End of cleaning variable ETime */
  /* End of cleaning variable DryTide8 */
  } /*if (f2py_success) of Salt*/
  /* End of cleaning variable Salt */
  } /*if (f2py_success) of Slat*/
  /* End of cleaning variable Slat */
  } /*if (f2py_success) of Slong*/
  /* End of cleaning variable Slong */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of DryTide8 ******************************/

/********************************* ShearTide9 *********************************/
static char doc_f2py_rout_EtideAsFunc_ShearTide9[] = "\
Function signature:\n\
  ShearTide9 = ShearTide9(ETime,Slat,Slong,Salt)\n\
Required arguments:\n"
"  ETime : input float\n"
"  Slat : input float\n"
"  Slong : input float\n"
"  Salt : input float\n"
"Return objects:\n"
"  ShearTide9 : float";
/* extern void F_WRAPPEDFUNC(sheartide9,SHEARTIDE9)(double*,float*,float*,float*,float*); */
static PyObject *f2py_rout_EtideAsFunc_ShearTide9(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,float*,float*,float*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  double ShearTide9 = 0;
  float ETime = 0;
  PyObject *ETime_capi = Py_None;
  float Slat = 0;
  PyObject *Slat_capi = Py_None;
  float Slong = 0;
  PyObject *Slong_capi = Py_None;
  float Salt = 0;
  PyObject *Salt_capi = Py_None;
  static char *capi_kwlist[] = {"ETime","Slat","Slong","Salt",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO:EtideAsFunc.ShearTide9",\
    capi_kwlist,&ETime_capi,&Slat_capi,&Slong_capi,&Salt_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable ShearTide9 */
  /* Processing variable Slong */
    f2py_success = float_from_pyobj(&Slong,Slong_capi,"EtideAsFunc.ShearTide9() 3rd argument (Slong) can't be converted to float");
  if (f2py_success) {
  /* Processing variable Slat */
    f2py_success = float_from_pyobj(&Slat,Slat_capi,"EtideAsFunc.ShearTide9() 2nd argument (Slat) can't be converted to float");
  if (f2py_success) {
  /* Processing variable Salt */
    f2py_success = float_from_pyobj(&Salt,Salt_capi,"EtideAsFunc.ShearTide9() 4th argument (Salt) can't be converted to float");
  if (f2py_success) {
  /* Processing variable ETime */
    f2py_success = float_from_pyobj(&ETime,ETime_capi,"EtideAsFunc.ShearTide9() 1st argument (ETime) can't be converted to float");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(&ShearTide9,&ETime,&Slat,&Slong,&Salt);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("d",ShearTide9);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of ETime*/
  /* End of cleaning variable ETime */
  } /*if (f2py_success) of Salt*/
  /* End of cleaning variable Salt */
  } /*if (f2py_success) of Slat*/
  /* End of cleaning variable Slat */
  } /*if (f2py_success) of Slong*/
  /* End of cleaning variable Slong */
  /* End of cleaning variable ShearTide9 */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/***************************** end of ShearTide9 *****************************/

/*********************************** Ntide1 ***********************************/
static char doc_f2py_rout_EtideAsFunc_Ntide1[] = "\
Function signature:\n\
  Ntide1(ETime,Astron)\n\
Required arguments:\n"
"  ETime : input float\n"
"  Astron : input float";
/* extern void F_FUNC(Ntide1,NTIDE1)(float*,float*); */
static PyObject *f2py_rout_EtideAsFunc_Ntide1(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  float ETime = 0;
  PyObject *ETime_capi = Py_None;
  float Astron = 0;
  PyObject *Astron_capi = Py_None;
  static char *capi_kwlist[] = {"ETime","Astron",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OO:EtideAsFunc.Ntide1",\
    capi_kwlist,&ETime_capi,&Astron_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable ETime */
    f2py_success = float_from_pyobj(&ETime,ETime_capi,"EtideAsFunc.Ntide1() 1st argument (ETime) can't be converted to float");
  if (f2py_success) {
  /* Processing variable Astron */
    f2py_success = float_from_pyobj(&Astron,Astron_capi,"EtideAsFunc.Ntide1() 2nd argument (Astron) can't be converted to float");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&ETime,&Astron);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of Astron*/
  /* End of cleaning variable Astron */
  } /*if (f2py_success) of ETime*/
  /* End of cleaning variable ETime */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of Ntide1 *******************************/

/************************************ Tid2 ************************************/
static char doc_f2py_rout_EtideAsFunc_Tid2[] = "\
Function signature:\n\
  Tid2 = Tid2(SLAT,SLONG,SH,KIND,ALPHA,astron)\n\
Required arguments:\n"
"  SLAT : input float\n"
"  SLONG : input float\n"
"  SH : input float\n"
"  KIND : input int\n"
"  ALPHA : input float\n"
"  astron : input float\n"
"Return objects:\n"
"  Tid2 : float";
/* extern void F_WRAPPEDFUNC(tid2,TID2)(float*,float*,float*,float*,int*,float*,float*); */
static PyObject *f2py_rout_EtideAsFunc_Tid2(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,float*,float*,float*,int*,float*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  float Tid2 = 0;
  float SLAT = 0;
  PyObject *SLAT_capi = Py_None;
  float SLONG = 0;
  PyObject *SLONG_capi = Py_None;
  float SH = 0;
  PyObject *SH_capi = Py_None;
  int KIND = 0;
  PyObject *KIND_capi = Py_None;
  float ALPHA = 0;
  PyObject *ALPHA_capi = Py_None;
  float astron = 0;
  PyObject *astron_capi = Py_None;
  static char *capi_kwlist[] = {"SLAT","SLONG","SH","KIND","ALPHA","astron",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOO:EtideAsFunc.Tid2",\
    capi_kwlist,&SLAT_capi,&SLONG_capi,&SH_capi,&KIND_capi,&ALPHA_capi,&astron_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable KIND */
    f2py_success = int_from_pyobj(&KIND,KIND_capi,"EtideAsFunc.Tid2() 4th argument (KIND) can't be converted to int");
  if (f2py_success) {
  /* Processing variable Tid2 */
  /* Processing variable SLAT */
    f2py_success = float_from_pyobj(&SLAT,SLAT_capi,"EtideAsFunc.Tid2() 1st argument (SLAT) can't be converted to float");
  if (f2py_success) {
  /* Processing variable SH */
    f2py_success = float_from_pyobj(&SH,SH_capi,"EtideAsFunc.Tid2() 3rd argument (SH) can't be converted to float");
  if (f2py_success) {
  /* Processing variable astron */
    f2py_success = float_from_pyobj(&astron,astron_capi,"EtideAsFunc.Tid2() 6th argument (astron) can't be converted to float");
  if (f2py_success) {
  /* Processing variable SLONG */
    f2py_success = float_from_pyobj(&SLONG,SLONG_capi,"EtideAsFunc.Tid2() 2nd argument (SLONG) can't be converted to float");
  if (f2py_success) {
  /* Processing variable ALPHA */
    f2py_success = float_from_pyobj(&ALPHA,ALPHA_capi,"EtideAsFunc.Tid2() 5th argument (ALPHA) can't be converted to float");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(&Tid2,&SLAT,&SLONG,&SH,&KIND,&ALPHA,&astron);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("f",Tid2);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of ALPHA*/
  /* End of cleaning variable ALPHA */
  } /*if (f2py_success) of SLONG*/
  /* End of cleaning variable SLONG */
  } /*if (f2py_success) of astron*/
  /* End of cleaning variable astron */
  } /*if (f2py_success) of SH*/
  /* End of cleaning variable SH */
  } /*if (f2py_success) of SLAT*/
  /* End of cleaning variable SLAT */
  /* End of cleaning variable Tid2 */
  } /*if (f2py_success) of KIND*/
  /* End of cleaning variable KIND */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************** end of Tid2 ********************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"FirstHorzTideStrain3",-1,{{-1}},0,(char *)F_WRAPPEDFUNC(firsthorztidestrain3,FIRSTHORZTIDESTRAIN3),(f2py_init_func)f2py_rout_EtideAsFunc_FirstHorzTideStrain3,doc_f2py_rout_EtideAsFunc_FirstHorzTideStrain3},
  {"SecondHorzTideStrain4",-1,{{-1}},0,(char *)F_WRAPPEDFUNC(secondhorztidestrain4,SECONDHORZTIDESTRAIN4),(f2py_init_func)f2py_rout_EtideAsFunc_SecondHorzTideStrain4,doc_f2py_rout_EtideAsFunc_SecondHorzTideStrain4},
  {"GravityTide6",-1,{{-1}},0,(char *)F_WRAPPEDFUNC(gravitytide6,GRAVITYTIDE6),(f2py_init_func)f2py_rout_EtideAsFunc_GravityTide6,doc_f2py_rout_EtideAsFunc_GravityTide6},
  {"TiltTide7",-1,{{-1}},0,(char *)F_WRAPPEDFUNC(tilttide7,TILTTIDE7),(f2py_init_func)f2py_rout_EtideAsFunc_TiltTide7,doc_f2py_rout_EtideAsFunc_TiltTide7},
  {"DryTide8",-1,{{-1}},0,(char *)F_WRAPPEDFUNC(drytide8,DRYTIDE8),(f2py_init_func)f2py_rout_EtideAsFunc_DryTide8,doc_f2py_rout_EtideAsFunc_DryTide8},
  {"ShearTide9",-1,{{-1}},0,(char *)F_WRAPPEDFUNC(sheartide9,SHEARTIDE9),(f2py_init_func)f2py_rout_EtideAsFunc_ShearTide9,doc_f2py_rout_EtideAsFunc_ShearTide9},
  {"Ntide1",-1,{{-1}},0,(char *)F_FUNC(Ntide1,NTIDE1),(f2py_init_func)f2py_rout_EtideAsFunc_Ntide1,doc_f2py_rout_EtideAsFunc_Ntide1},
  {"Tid2",-1,{{-1}},0,(char *)F_WRAPPEDFUNC(tid2,TID2),(f2py_init_func)f2py_rout_EtideAsFunc_Tid2,doc_f2py_rout_EtideAsFunc_Tid2},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "EtideAsFunc",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyObject *PyInit_EtideAsFunc(void) {
#else
#define RETVAL
PyMODINIT_FUNC initEtideAsFunc(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = EtideAsFunc_module = PyModule_Create(&moduledef);
#else
  m = EtideAsFunc_module = Py_InitModule("EtideAsFunc", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module EtideAsFunc (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'EtideAsFunc' is auto-generated with f2py (version:2).\nFunctions:\n"
"  FirstHorzTideStrain3 = FirstHorzTideStrain3(ETime,Slat,Slong,Salt,Azim)\n"
"  SecondHorzTideStrain4 = SecondHorzTideStrain4(ETime,Slat,Slong,Salt)\n"
"  GravityTide6 = GravityTide6(ETime,Slat,Slong,Salt)\n"
"  TiltTide7 = TiltTide7(ETime,Slat,Slong,Salt)\n"
"  DryTide8 = DryTide8(ETime,Slat,Slong,Salt)\n"
"  ShearTide9 = ShearTide9(ETime,Slat,Slong,Salt)\n"
"  Ntide1(ETime,Astron)\n"
"  Tid2 = Tid2(SLAT,SLONG,SH,KIND,ALPHA,astron)\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  EtideAsFunc_error = PyErr_NewException ("EtideAsFunc.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));

    {
      extern double F_FUNC(firsthorztidestrain3,FIRSTHORZTIDESTRAIN3)(void);
      PyObject* o = PyDict_GetItemString(d,"FirstHorzTideStrain3");
      PyObject_SetAttrString(o,"_cpointer", F2PyCapsule_FromVoidPtr((void*)F_FUNC(firsthorztidestrain3,FIRSTHORZTIDESTRAIN3),NULL));
#if PY_VERSION_HEX >= 0x03000000
      PyObject_SetAttrString(o,"__name__", PyUnicode_FromString("FirstHorzTideStrain3"));
#else
      PyObject_SetAttrString(o,"__name__", PyString_FromString("FirstHorzTideStrain3"));
#endif
    }
    

    {
      extern double F_FUNC(secondhorztidestrain4,SECONDHORZTIDESTRAIN4)(void);
      PyObject* o = PyDict_GetItemString(d,"SecondHorzTideStrain4");
      PyObject_SetAttrString(o,"_cpointer", F2PyCapsule_FromVoidPtr((void*)F_FUNC(secondhorztidestrain4,SECONDHORZTIDESTRAIN4),NULL));
#if PY_VERSION_HEX >= 0x03000000
      PyObject_SetAttrString(o,"__name__", PyUnicode_FromString("SecondHorzTideStrain4"));
#else
      PyObject_SetAttrString(o,"__name__", PyString_FromString("SecondHorzTideStrain4"));
#endif
    }
    

    {
      extern double F_FUNC(gravitytide6,GRAVITYTIDE6)(void);
      PyObject* o = PyDict_GetItemString(d,"GravityTide6");
      PyObject_SetAttrString(o,"_cpointer", F2PyCapsule_FromVoidPtr((void*)F_FUNC(gravitytide6,GRAVITYTIDE6),NULL));
#if PY_VERSION_HEX >= 0x03000000
      PyObject_SetAttrString(o,"__name__", PyUnicode_FromString("GravityTide6"));
#else
      PyObject_SetAttrString(o,"__name__", PyString_FromString("GravityTide6"));
#endif
    }
    

    {
      extern double F_FUNC(tilttide7,TILTTIDE7)(void);
      PyObject* o = PyDict_GetItemString(d,"TiltTide7");
      PyObject_SetAttrString(o,"_cpointer", F2PyCapsule_FromVoidPtr((void*)F_FUNC(tilttide7,TILTTIDE7),NULL));
#if PY_VERSION_HEX >= 0x03000000
      PyObject_SetAttrString(o,"__name__", PyUnicode_FromString("TiltTide7"));
#else
      PyObject_SetAttrString(o,"__name__", PyString_FromString("TiltTide7"));
#endif
    }
    

    {
      extern double F_FUNC(drytide8,DRYTIDE8)(void);
      PyObject* o = PyDict_GetItemString(d,"DryTide8");
      PyObject_SetAttrString(o,"_cpointer", F2PyCapsule_FromVoidPtr((void*)F_FUNC(drytide8,DRYTIDE8),NULL));
#if PY_VERSION_HEX >= 0x03000000
      PyObject_SetAttrString(o,"__name__", PyUnicode_FromString("DryTide8"));
#else
      PyObject_SetAttrString(o,"__name__", PyString_FromString("DryTide8"));
#endif
    }
    

    {
      extern double F_FUNC(sheartide9,SHEARTIDE9)(void);
      PyObject* o = PyDict_GetItemString(d,"ShearTide9");
      PyObject_SetAttrString(o,"_cpointer", F2PyCapsule_FromVoidPtr((void*)F_FUNC(sheartide9,SHEARTIDE9),NULL));
#if PY_VERSION_HEX >= 0x03000000
      PyObject_SetAttrString(o,"__name__", PyUnicode_FromString("ShearTide9"));
#else
      PyObject_SetAttrString(o,"__name__", PyString_FromString("ShearTide9"));
#endif
    }
    


    {
      extern float F_FUNC(tid2,TID2)(void);
      PyObject* o = PyDict_GetItemString(d,"Tid2");
      PyObject_SetAttrString(o,"_cpointer", F2PyCapsule_FromVoidPtr((void*)F_FUNC(tid2,TID2),NULL));
#if PY_VERSION_HEX >= 0x03000000
      PyObject_SetAttrString(o,"__name__", PyUnicode_FromString("Tid2"));
#else
      PyObject_SetAttrString(o,"__name__", PyString_FromString("Tid2"));
#endif
    }
    
/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"EtideAsFunc");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
