atm_file            	NONE
atmosphere          	0
base_pressure       	0.0
batch_drift_plot    	yes
detrend             	42,48,43,60,61,64,49,66,87,24,27,21,22,23,47,44,45,28,29,2,7,6,9,8,39,11,10,13,14,17,16,18,31,30,50,32,
drift               	1
dz                  	0
gmt_offset          	None
grav_samples        	0
instrument_drift    	1
longman             	1
max_recs            	-1
meter_file          	IGNORED
meter_type          	CG-5
order               	6
out_name            	None
parm_file           	C:/Users/CHRISTIANHARDWICK/Desktop/gravity_data/Pavant/cg52.par
processed_view      	0
raw_file            	C:/Users/CHRISTIANHARDWICK/Desktop/gravity_data/Pavant/cg52_Sep152011.txt
raw_view            	0
ref_type            	1
ref_val             	PRES1
sigma_threshhold    	0.25
skip                	3.0
slope_threshhold    	2.7e-005
start_order         	0
tamura              	1
tare_file           	None
temp_correct        	0
temp_correct_debug  	0
temp_remove         	0
temp_threshhold     	0
temp_threshhold_drop	0
thiele              	0
thiele_filt_radius  	30
thiele_tolerance    	1e-07
tilt                	0
tilt_corr           	0
weighted_drift      	1
xe                  	0.0
ye                  	0.0
